##################
# Required items #
##################
# You are required to fill the option below,
# or this channel will not work.

# Telegram bot token.
# This is the token you obtained from BotFather
token: "token"
# List of Telegram User IDs of admins
# ETM will only process messages and commands from users
# listed below. This ID can be obtained from various ways
# on Telegram.
admins:
- userid

##################
# Optional items #
##################
# The following options are optional. Omissiond of this section
# will only affect an additional part of functionality of
# this channel.

# API tokens required for speech recognition
#speech_api:
    # Microsoft (Bing) speech recognition token
    # API key can be obtained from
    # https://azure.microsoft.com/en-us/try/cognitive-services/
    #bing: "VOICE_RECOGNITION_TOKEN"
    # Baidu speech recognition token
    # API key can be obtained from
    # http://yuyin.baidu.com/
    #baidu:
        #app_id: 123456
        #api_key: "API_KEY_GOES_HERE"
        #secret_key: "SECRET_KEY_GOES_HERE"

